CREATE TABLE CAR(
CAR_ID NUMBER PRIMARY KEY,
CAR_NAME VARCHAR2(50),
CAR_INFORMATION VARCHAR2(500),
CAR_PRICE NUMBER(*,2),
CAR_STATUS VARCHAR2(50) DEFAULT 'Available');

--ADDING CONSTRAINT FOR CAR PRICE
ALTER TABLE CAR
ADD CONSTRAINT CAR_CAR_PRICE_POSITIVE
CHECK(CAR_PRICE>0);

ALTER TABLE CAR
MODIFY CAR_PRICE NUMBER(*,2);

CREATE TABLE CUSTOMER(
CUSTOMER_ID NUMBER PRIMARY KEY,
CUSTOMER_USERNAME VARCHAR2(50)UNIQUE NOT NULL,
CUSTOMER_PASSWORD VARCHAR2(50),
CUSTOMER_NAME VARCHAR2(100),
CUSTOMER_PAYMENTS NUMERIC(7,2) DEFAULT 0,
CUSTOMER_BALANCE NUMERIC(7,2) DEFAULT 0
);

ALTER TABLE CUSTOMER
MODIFY CUSTOMER_PAYMENTS NUMBER(*,2);
ALTER TABLE CUSTOMER
MODIFY CUSTOMER_BALANCE NUMBER(*,2);

ALTER TABLE CUSTOMER
DROP CONSTRAINT CUSTOMER_PAYMENTS_POSITIVE
CHECK(CUSTOMER_PAYMENTS>0);

CREATE TABLE EMPLOYEE(
EMPLOYEE_ID NUMBER PRIMARY KEY,
EMPLOYEE_USERNAME VARCHAR2(50)UNIQUE NOT NULL,
EMPLOYEE_PASSWORD VARCHAR2(50),
EMPLOYEE_NAME VARCHAR2(100)
);

CREATE TABLE OFFER(
OFFER_ID NUMBER PRIMARY KEY,
CAR_ID NUMBER NOT NULL,
CUSTOMER_ID NUMBER NOT NULL,
CAR_NAME VARCHAR2(50),
CAR_PRICE NUMBER(*,2),
CUSTOMER_NAME VARCHAR2(50),
OFFER_STATUS VARCHAR2(50),
CAR_REMAIN NUMBER(*,2) DEFAULT 0,
MONTHLY24 NUMBER(*,2) DEFAULT 0,
MONTHLY36 NUMBER(*,2) DEFAULT 0
);

--ADDING CONSTRAINT FOR CAR PRICE
ALTER TABLE OFFER
ADD CONSTRAINT CK_OFFER_CAR_PRICE_POSITIVE
CHECK(CAR_PRICE>0);

--ADDING FOREIGN KEY
ALTER TABLE OFFER
ADD CONSTRAINT FK_OFFER_CAR
FOREIGN KEY(CAR_ID) REFERENCES CAR(CAR_ID);

ALTER TABLE OFFER
ADD CONSTRAINT FK_OFFER_CUSTOMER
FOREIGN KEY(CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID);

--Add three new colums
ALTER TABLE OFFER
ADD CAR_REMAIN NUMERIC(7,2) DEFAULT 0;

ALTER TABLE OFFER
ADD MONTHLY24 NUMERIC(7,2) DEFAULT 0;

ALTER TABLE OFFER
ADD MONTHLY36 NUMERIC(7,2) DEFAULT 0;

ALTER TABLE OFFER
MODIFY CAR_PRICE NUMBER(*,2);
ALTER TABLE OFFER
MODIFY CAR_REMAIN NUMBER(*,2);
ALTER TABLE OFFER
MODIFY MONTHLY24 NUMBER(*,2);
ALTER TABLE OFFER
MODIFY MONTHLY36 NUMBER(*,2);

--SEQUENCE
CREATE SEQUENCE MYSEQ;
UPDATE CAR SET CAR_ID = MYSEQ.NEXTVAL;
CREATE SEQUENCE MYSEQ2;
UPDATE EMPLOYEE SET EMPLOYEE_ID = MYSEQ2.NEXTVAL;
CREATE SEQUENCE MYSEQ3;
UPDATE CUSTOMER SET CUSTOMER_ID = MYSEQ3.NEXTVAL;
CREATE SEQUENCE MYSEQ4;
UPDATE OFFER SET OFFER_ID = MYSEQ4.NEXTVAL;

--CREATE OR REPLACE PROCEDURE CARPRO
--(CAR_NAME IN VARCHAR2, CAR_INFORMATION IN VARCHAR2, CAR_PRICE IN NUMERIC)
--AS
--BEGIN
--INSERT INTO CAR VALUES(MYSEQ.NEXTVAL, CAR_NAME, CAR_INFORMATION,CAR_PRICE,'Available');
--COMMIT;
--END;
--/
--
--EXECUTE CARPRO('HondaAccord','2008,EX_L,Loaded,LOW MILES',6995.99);
--EXECUTE CARPRO('Toyoya','2008,4Runner Sport,85K MILES',16998.00);

SELECT * FROM CAR;

DROP TABLE CAR;
DROP TABLE CUSTOMER;
DROP TABLE EMPLOYEE;
DROP TABLE OFFER;

UPDATE CAR SET CAR_NAME = 'NISSAN2' WHERE CAR_ID = 'CAR003';
SELECT CUSTOMER_NAME FROM CUSTOMER WHERE CUSTOMER_ID = 2;
INSERT INTO OFFER VALUES(MYSEQ4.NEXTVAL,21,2,'Toyoya',16998.0,'Mike','Pending');
UPDATE CAR SET CAR_STATUS = 'Pending' WHERE CAR_ID = 21;
SELECT * FROM OFFER WHERE CUSTOMER_ID = 2;
UPDATE OFFER SET OFFER_STATUS = 'Pendng' WHERE OFFER_ID = 4;
UPDATE OFFER SET OFFER_STATUS = 'Pending' WHERE OFFER_ID = 2;
SELECT * FROM OFFER
DELETE FROM CAR WHERE CAR_ID = "+id+"
DELETE FROM OFFER WHERE OFFER_ID = 2